spring:
  security:
    filter:
      dispatcher-types: request
    oauth2:
      client:
        registration:
          github :
            client-id: d0797abc068a3693fe26
            client-secret: e79d87694a09d16d6870644750e59aee26b0fe89
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
          google :
            client-id: 152773267174-q79s8e68qmv6kof4m57tsm8btg4lld25.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - profile
              - email
          naver :
            client-id: QGTNlYyb0W6QbHQDQWMl
            client-secret: qCggzbFf_s
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - profile_image
              - email
              
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moa2?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

app:
  jwt:
    secret: "ddhjfkafdshjlflhjdas3288998ksjkskj28kjas829uaw89242kl4jk12j6jk1jjjsa28jdska289kj289jdak282313212412312"
    access-token-validity-in-seconds: 43200 # 12 hours
    refresh-token-validity-in-seconds: 604800 # 1 week
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect