oauth2 :
  user :
    github :
      client-id : d0797abc068a3693fe26
      client-secret : e79d87694a09d16d6870644750e59aee26b0fe89
      redirect-uri : http://localhost:3000/oauth2/callback/github
    google :
      client-id : 152773267174-q79s8e68qmv6kof4m57tsm8btg4lld25.apps.googleusercontent.com
      client-secret : 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
      redirect-uri : http://localhost:3000/oauth2/callback/google
    naver :
      client-id : QGTNlYyb0W6QbHQDQWMl
      client-secret: qCggzbFf_s
      redirect-uri : http://localhost:3000/oauth2/callback/naver

  provider :
    github:
      token-uri: https://github.com/login/oauth/access_token
      user-info-uri: https://api.github.com/user
    google:
      token-uri: https://www.googleapis.com/oauth2/v4/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
    naver:
      token-uri: https://nid.naver.com/oauth2.0/token
      user-info-uri: https://openapi.naver.com/v1/nid/me

