spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moa?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: kims503050ok#

  redis:
    host: localhost
    port: 6379

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  secret: "dnflahencnldjqtjdrhdgkwkekemfwhgdmseprkftndltrlfmfqkfkqslekghkdlxldrkatkgkqslek"
